// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"nn8eqql1mh","name":"TasksAPI","description":"","endpoint":"https://nn8eqql1mh.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/tasks","/tasks/123"]},{"id":"j8qfbvq1a1","name":"ProjectsAPI","description":"","endpoint":"https://j8qfbvq1a1.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/projects","/projects/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:9ec33062-eea4-4d36-894e-d7331bfa7c02',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'jokeme-hosting-mobilehub-1639871442',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd37fstsrhj92u4.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"jokeme-mobilehub-1639871442-projects","attributes":[{"name":"projectId","type":"S"},{"name":"month","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"projectId","rangeKey":"month"},{"tableName":"jokeme-mobilehub-1639871442-tasks","attributes":[{"name":"userId","type":"S"},{"name":"taskId","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"taskId"}],
    'aws_project_id': 'f3b67ce2-c643-4732-bc12-defcc91c1940',
    'aws_project_name': 'joke-me',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'jokeme-deployments-mobilehub-1639871442',
    'aws_resource_name_prefix': 'jokeme-mobilehub-1639871442',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_gmJv6Qvde',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2vi4b6776t1ko3duphh7bqquk6',
}

export default awsmobile;
